---
title: "data_exploration"
format: html
editor: visual
---

## Data Exploration

## Import Libraries

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sf) 
library(stars)
```

## Download Data

```{r}
envir_saf <- read_csv(here::here('data','Envir_safety_inc.csv'))
fam_poverty <- read_csv(here::here('data', 'Fam_below_poverty.csv'))

```

## Data Wrangling

Families Below Poverty Data

```{r}
# Change column names 
for(i in seq_along(fam_poverty)){
  colnames(fam_poverty)[i] <- paste0(fam_poverty[1,i]) # Moving data from the 1st row to the column name 
}

colnames(fam_poverty)[1] <- fam_poverty[2,1] # Changing first row name 

# Remove Rows 
fam_poverty <- fam_poverty[-c(1,2), ]

```

Environmental School Safety Data

```{r}
# Change column names 

year_list <- c(0, 2023, 2023, 2022, 2022, 2021, 2021, 2020, 2020, 2019, 2019, 2018, 2018, 2017, 2017, 2016, 2016, 2015, 2015, 2014, 2014, 2013, 2013)

for (i in seq_along(envir_saf)) {
  colnames(envir_saf)[i] <- paste0(envir_saf[2, i], "_", year_list[i]) # Change column names based on other row and year 
}

colnames(envir_saf)[1] <- envir_saf[2,1] # Change 1 column name 

# Remove Rows 
envir_saf <- envir_saf[-c(1,2), ]

```

Add region

```{r}
# New column via region 

fam_poverty <- fam_poverty %>% 
  mutate(region = case_when (
    
    County %in% c('Jefferson', 'Leon', 'Wakulla', 'Franklin', 'Liberty', 'Gadsden', 'Jackson', 'Calhoun', 'Gulf', 'Bay', 'Washington', 'Holmes', 'Walton', 'Okaloosa', 'Santa Rosa', 'Escambia') ~ "northwest",
  
    County %in% c('Alachua', 'Gilchrist', 'Marion', 'Columbia', 'Bradford', 'Dixie', 'Hamilton', 'Lafayette', 'Levy', 'Madison', 'Suwannee', 'Taylor', 'Union') ~ "north_central",
  
    County %in% c('Baker', 'Clay', 'Duval', 'Flagler', 'Nassau', 'Putnam', 'St. Johns') ~ "northeast",
    
    County %in% c('Charlotte', 'DeSoto', 'Sarasota', 'Manatee', 'Hillsborough', 'Pinellas', 'Pasco', 'Hernando', 'Citrus') ~ "central_west",
    
   County %in% c('Hardee', 'Highlands', 'Okeechobee', 'Polk', 'Osceola', 'Orange', 'Seminole', 'Lake', 'Sumter') ~ "central",
    
    County %in% c('Martin', 'St. Lucie', 'Indian River', 'Brevard', 'Volusia') ~ "central_east",
    
    County %in% c('Monroe', 'Collier', 'Hendry', 'Lee', 'Glades') ~ 'southwest',
    
    County %in% c('Miami-Dade', 'Broward', 'Palm Beach') ~ 'southeast',
    
    County %in% c('Islamorada', 'Marathon', 'Key Largo', 'Key West') ~ 'keys'
   
  ))

```

Change Column Data Types

```{r}
# Change columns to numeric 
fam_poverty[, c(2:11)] <- lapply(fam_poverty[, c(2:11)], as.numeric)

str(fam_poverty)

```

pivot longer the data fam_povery data

```{r}
fam_pov_longer <- pivot_longer(fam_poverty, 
             cols = `2023`:`2014`, 
             names_to = 'year', 
             values_to = "percent")

```

Group by region fam_poverty data

```{r}
region_pov <- fam_pov_longer %>% 
  group_by(region) %>% 
  summarise(mean_percent = mean(percent, na.rm = TRUE))

```

```{r}
ggplot(region_pov, 
       aes(x = region, 
           y = mean_percent, 
           fill = region)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  

```

Join data

```{r}
# poverty = x 
# environmental school safely incidents 

join_df <- full_join(fam_poverty, envir_saf, by = "County")

```

```{r}
ggplot(join_df, 
       aes(x = `2023`, 
           y = Rate_2023)) + 
  geom_point() + 
  labs(title = "Environmental School Incidents In Comparison to Families Below the Poverty", 
       x = "Environmental School Incidents", 
       y = "Rates of Families Living under the Poverty")

```

\
